trigger:
  branches:
    include:
    - master

parameters:
- name: SignTypeSelection
  displayName: Sign type
  type: string
  default: Real
  values: [ 'Test', 'Real' ]

  variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
  SigningType: ${{ parameters.SignTypeSelection }}

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2019
  steps:
 - template: azure-pipelines-common-windows.yml
 - task: PowerShell@1
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: 'Push VSIX'
    inputs:
      scriptType: inlineScript
      inlineScript: |
        # Setting these environment variables because they are used in the script for the upload endpoint: 
     
        $env:APPVEYOR_REPO_PROVIDER = "github"
        $env:APPVEYOR_REPO_NAME = "microsoft/dotnet-apiport"

- job: Linux
  pool:
    vmImage: Ubuntu 18.04
  variables:
    BuildNetCoreAppTarget: netcoreapp3.1
    RestoreBuildProjects: src/ApiPort/ApiPort/*.csproj
   - template: azure-pipelines-common-linux.yml
