trigger:
  branches:
    include:
    - master
    - dev

parameters:
- name: SignTypeSelection
  displayName: Sign type
  type: string
  default: Test
  values: [ 'Test', 'Real' ]

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
  SigningType: ${{ parameters.SignTypeSelection }}

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2019
  steps:
 - template: azure-pipelines-common-windows.yml

- job: Linux
  pool:
    vmImage: Ubuntu 18.04
  variables:
    BuildNetCoreAppTarget: netcoreapp3.1
    RestoreBuildProjects: src/ApiPort/ApiPort/*.csproj
  steps:
   - template: azure-pipelines-common-linux.yml

